services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5173:5173"  # Fix port mapping (Host 5003 → Container 5000)
    env_file: ./.env  # Load environment variables
    volumes:
      - .:/app  # Mount the whole project
      # - /app/node_modules  # Prevent overwriting node_modules
    restart: always  # Restart on failure
